<div class="container-960 bg-page-bar">
  <div class="page-bar">
    <h1 class="title-page">
      404 error page
    </h1>
    <div class="clear"></div>
  </div>
</div>

<div class="container-960 content-page-home">
  <div class="container-404">
    <span class="hex-404 left-404"></span>
    <div class="the-404">
      404<span>error</span>
    </div>
    <span class="hex-404 right-404"></span>
    <div class="clear"></div>
    <p>
      This file may have been moved or deleted. Be sure to check your spelling
    </p>
  </div>
  <div class="clear"></div>
</div>